/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_board_serial                   20
#define gattdb_board_rev                      22
#define gattdb_firmware_rev                   24
#define gattdb_system_id                      26
#define gattdb_es_sound_level                 29
#define gattdb_es_uvindex                     31
#define gattdb_es_ambient_light               33
#define gattdb_es_pressure                    35
#define gattdb_es_temperature                 37
#define gattdb_es_humidity                    39
#define gattdb_ui_rgbleds                     42
#define gattdb_iaq_eco2                       45
#define gattdb_iaq_tvoc                       47
#define gattdb_imu_acceleration               50
#define gattdb_imu_orientation                53
#define gattdb_imu_control_point              56
#define gattdb_ota_control                    60
#define gattdb_aio_digital_in                 63
#define gattdb_aio_num_of_digitals_in         66
#define gattdb_aio_digital_out                68
#define gattdb_aio_num_of_digitals_out        70
#define gattdb_batt_measurement               73
#define gattdb_power_source_type              77
#define gattdb_hall_state                     80
#define gattdb_hall_field_strength            83
#define gattdb_hall_control_point             86


#endif // __GATT_DB_H
